package api

import (
	"fmt"

	"github.com/ReyOrtiz/reddit-content-analyzer/internal/infra/config"
	"github.com/ReyOrtiz/reddit-content-analyzer/internal/services"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	
	_ "github.com/ReyOrtiz/reddit-content-analyzer/docs" // docs is generated by Swag CLI, you have to import it.
)

func StartServer() {
	cfg := config.GetConfig()
	relevanceService := services.NewRelevanceService()
	relevanceHandler := NewRelevanceHandler(relevanceService)

	router := gin.Default()
	router.POST("/v1/reddit/relevance/search", relevanceHandler.GetRelevantPosts)
	
	// Swagger documentation endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	
	router.Run(fmt.Sprintf(":%s", cfg.GetString("api.port")))
}
