// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_reddit

import (
	"github.com/ReyOrtiz/reddit-content-analyzer/internal/infra/reddit"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// GetPosts provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) GetPosts(subreddit string, limit int) (*reddit.RedditResponse, error) {
	ret := _mock.Called(subreddit, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 *reddit.RedditResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (*reddit.RedditResponse, error)); ok {
		return returnFunc(subreddit, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) *reddit.RedditResponse); ok {
		r0 = returnFunc(subreddit, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reddit.RedditResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(subreddit, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockClientInterface_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - subreddit string
//   - limit int
func (_e *MockClientInterface_Expecter) GetPosts(subreddit interface{}, limit interface{}) *MockClientInterface_GetPosts_Call {
	return &MockClientInterface_GetPosts_Call{Call: _e.mock.On("GetPosts", subreddit, limit)}
}

func (_c *MockClientInterface_GetPosts_Call) Run(run func(subreddit string, limit int)) *MockClientInterface_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientInterface_GetPosts_Call) Return(redditResponse *reddit.RedditResponse, err error) *MockClientInterface_GetPosts_Call {
	_c.Call.Return(redditResponse, err)
	return _c
}

func (_c *MockClientInterface_GetPosts_Call) RunAndReturn(run func(subreddit string, limit int) (*reddit.RedditResponse, error)) *MockClientInterface_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPosts provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) SearchPosts(subreddit string, query string, limit int) (*reddit.RedditResponse, error) {
	ret := _mock.Called(subreddit, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchPosts")
	}

	var r0 *reddit.RedditResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int) (*reddit.RedditResponse, error)); ok {
		return returnFunc(subreddit, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int) *reddit.RedditResponse); ok {
		r0 = returnFunc(subreddit, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reddit.RedditResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = returnFunc(subreddit, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_SearchPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPosts'
type MockClientInterface_SearchPosts_Call struct {
	*mock.Call
}

// SearchPosts is a helper method to define mock.On call
//   - subreddit string
//   - query string
//   - limit int
func (_e *MockClientInterface_Expecter) SearchPosts(subreddit interface{}, query interface{}, limit interface{}) *MockClientInterface_SearchPosts_Call {
	return &MockClientInterface_SearchPosts_Call{Call: _e.mock.On("SearchPosts", subreddit, query, limit)}
}

func (_c *MockClientInterface_SearchPosts_Call) Run(run func(subreddit string, query string, limit int)) *MockClientInterface_SearchPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientInterface_SearchPosts_Call) Return(redditResponse *reddit.RedditResponse, err error) *MockClientInterface_SearchPosts_Call {
	_c.Call.Return(redditResponse, err)
	return _c
}

func (_c *MockClientInterface_SearchPosts_Call) RunAndReturn(run func(subreddit string, query string, limit int) (*reddit.RedditResponse, error)) *MockClientInterface_SearchPosts_Call {
	_c.Call.Return(run)
	return _c
}
