// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_services

import (
	"context"

	"github.com/ReyOrtiz/reddit-content-analyzer/internal/contracts"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRelevanceService creates a new instance of MockRelevanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelevanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelevanceService {
	mock := &MockRelevanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelevanceService is an autogenerated mock type for the RelevanceService type
type MockRelevanceService struct {
	mock.Mock
}

type MockRelevanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelevanceService) EXPECT() *MockRelevanceService_Expecter {
	return &MockRelevanceService_Expecter{mock: &_m.Mock}
}

// GetRelevantPosts provides a mock function for the type MockRelevanceService
func (_mock *MockRelevanceService) GetRelevantPosts(ctx context.Context, request contracts.RelevanceRequestDto) (contracts.RelevanceResponseDto, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetRelevantPosts")
	}

	var r0 contracts.RelevanceResponseDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, contracts.RelevanceRequestDto) (contracts.RelevanceResponseDto, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, contracts.RelevanceRequestDto) contracts.RelevanceResponseDto); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(contracts.RelevanceResponseDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, contracts.RelevanceRequestDto) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelevanceService_GetRelevantPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelevantPosts'
type MockRelevanceService_GetRelevantPosts_Call struct {
	*mock.Call
}

// GetRelevantPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - request contracts.RelevanceRequestDto
func (_e *MockRelevanceService_Expecter) GetRelevantPosts(ctx interface{}, request interface{}) *MockRelevanceService_GetRelevantPosts_Call {
	return &MockRelevanceService_GetRelevantPosts_Call{Call: _e.mock.On("GetRelevantPosts", ctx, request)}
}

func (_c *MockRelevanceService_GetRelevantPosts_Call) Run(run func(ctx context.Context, request contracts.RelevanceRequestDto)) *MockRelevanceService_GetRelevantPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 contracts.RelevanceRequestDto
		if args[1] != nil {
			arg1 = args[1].(contracts.RelevanceRequestDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelevanceService_GetRelevantPosts_Call) Return(relevanceResponseDto contracts.RelevanceResponseDto, err error) *MockRelevanceService_GetRelevantPosts_Call {
	_c.Call.Return(relevanceResponseDto, err)
	return _c
}

func (_c *MockRelevanceService_GetRelevantPosts_Call) RunAndReturn(run func(ctx context.Context, request contracts.RelevanceRequestDto) (contracts.RelevanceResponseDto, error)) *MockRelevanceService_GetRelevantPosts_Call {
	_c.Call.Return(run)
	return _c
}
