// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_llm

import (
	"context"

	"github.com/ReyOrtiz/reddit-content-analyzer/internal/infra/llm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) Chat(ctx context.Context, messages []llm.Message) (string, error) {
	ret := _mock.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []llm.Message) (string, error)); ok {
		return returnFunc(ctx, messages)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []llm.Message) string); ok {
		r0 = returnFunc(ctx, messages)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []llm.Message) error); ok {
		r1 = returnFunc(ctx, messages)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockClientInterface_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []llm.Message
func (_e *MockClientInterface_Expecter) Chat(ctx interface{}, messages interface{}) *MockClientInterface_Chat_Call {
	return &MockClientInterface_Chat_Call{Call: _e.mock.On("Chat", ctx, messages)}
}

func (_c *MockClientInterface_Chat_Call) Run(run func(ctx context.Context, messages []llm.Message)) *MockClientInterface_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []llm.Message
		if args[1] != nil {
			arg1 = args[1].([]llm.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientInterface_Chat_Call) Return(s string, err error) *MockClientInterface_Chat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClientInterface_Chat_Call) RunAndReturn(run func(ctx context.Context, messages []llm.Message) (string, error)) *MockClientInterface_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbedding provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) GetEmbedding(ctx context.Context, text string) ([]float32, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedding")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_GetEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedding'
type MockClientInterface_GetEmbedding_Call struct {
	*mock.Call
}

// GetEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockClientInterface_Expecter) GetEmbedding(ctx interface{}, text interface{}) *MockClientInterface_GetEmbedding_Call {
	return &MockClientInterface_GetEmbedding_Call{Call: _e.mock.On("GetEmbedding", ctx, text)}
}

func (_c *MockClientInterface_GetEmbedding_Call) Run(run func(ctx context.Context, text string)) *MockClientInterface_GetEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientInterface_GetEmbedding_Call) Return(float32s []float32, err error) *MockClientInterface_GetEmbedding_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockClientInterface_GetEmbedding_Call) RunAndReturn(run func(ctx context.Context, text string) ([]float32, error)) *MockClientInterface_GetEmbedding_Call {
	_c.Call.Return(run)
	return _c
}
